peaks=read.table("~/projects/HD/data/scratch/h3k4me3_peaks_union.signal.neighborhood.annotated.bed.xls", header=T)

attach(peaks)
# distance of peak to TSS
hist(pmax(pmin(distance_peakcenter2TSS, 1e4), -1e4), breaks=100)
hist(distance_peakcenter2TSS[distance_peakcenter2TSS < 2e3 & distance_peakcenter2TSS > -2e3], breaks=100, main=)
abline(v=c(-1000,1000), col='red', lty=2)


#################################################### (OLD VERSION) #############################################
peaks=read.table("significantPeaks.bed.inpromoter.tab", header=T)
#colnames(peaks)=c('chr',"start_peak", "end_peak", "length", "summit_pos", "tags_in_peak","pvalue_MACS","fold_enrichment", "FDR","summit_height","peak_type", "raw_read_1", "raw_read_2", "M","A", "pvalue_MAnorm","inpromoter")

pdf("h3k4me3_peaks.pdf", width=8, height=6, colormodel='cmyk')
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(peaks$A_rescaled, peaks$M_rescaled, col=rev(rainbow(nrow(peaks), start=0, end=4/6))[rank(peaks$pvalue_MAnorm)], pch='.', cex=.5, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("H3K4me3 peaks btw HD and Control (n=",nrow(peaks),")",sep=""))
image(1,1:nrow(peaks),matrix(data=1:nrow(peaks),ncol=nrow(peaks),nrow=1),col=rev(rainbow(nrow(peaks), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks$pvalue_MAnorm!=Inf & !is.na(peaks$pvalue_MAnorm)),length.out=length(seq(0,max(peaks$pvalue_MAnorm[peaks$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks$pvalue_MAnorm[peaks$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

peaks1=subset(peaks, FDR<10 & fold_enrichment>4)
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(peaks1$A_rescaled, peaks1$M_rescaled, col=rev(rainbow(nrow(peaks1), start=0, end=4/6))[rank(peaks1$pvalue_MAnorm)], pch='.', cex=.5, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Significant H3K4me3 peaks btw HD and Control (n=",nrow(peaks1),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

# proxiaml vs. distal
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(peaks1$A_rescaled, peaks1$M_rescaled, col=ifelse(peaks1$inpromoter=="proximal", '#00000088','#ff000088'), pch='.', cex=.5, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Significant H3K4me3 peaks btw HD and Control (n=",nrow(peaks1),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
n=c(sum(peaks1$inpromoter=="proximal"), sum(peaks1$inpromoter!="proximal"))
legend("topleft", paste(c("proximal peaks","distal peaks"), " (n=", n,")", sep=""), col=c('#00000088','#ff000088'), pch=20, bty='n')
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

# proximal peaks into different peak type (unique vs. common)
p1=subset(peaks1, inpromoter=="proximal")
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(subset(p1, peak_type=="common_peak1", c(A_rescaled, M_rescaled)), col='#0000aa66', pch=20, cex=.5, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Proximal H3K4me3 peaks (n=",nrow(p1),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
points(subset(p1, peak_type=="common_peak2", c(A_rescaled, M_rescaled)), col='#0000ff66', pch=20, cex=.5)
points(subset(p1, peak_type=="unique_peak1", c(A_rescaled, M_rescaled)), col='#ff000088', pch=20, cex=.5)
points(subset(p1, peak_type=="unique_peak2", c(A_rescaled, M_rescaled)), col='#00ff0088', pch=20, cex=.5)
n=table(p1$peak_type)
legend("topleft", paste(names(n), " (n=", n,")", sep=""), col=c('#0000aa66','#0000ff66', '#ff000088','#00ff0088'), pch=20, bty='n')
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

# distal peaks into different peak type (unique vs. common)
p2=subset(peaks1, inpromoter=="distal")
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(subset(p2, peak_type=="common_peak1", c(A_rescaled, M_rescaled)), col='#0000aa66', pch=20, cex=.5, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Distal H3K4me3 peaks (n=",nrow(p2),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
points(subset(p2, peak_type=="common_peak2", c(A_rescaled, M_rescaled)), col='#0000ff66', pch=20, cex=.5)
points(subset(p2, peak_type=="unique_peak1", c(A_rescaled, M_rescaled)), col='#ff000088', pch=20, cex=.5)
points(subset(p2, peak_type=="unique_peak2", c(A_rescaled, M_rescaled)), col='#00ff0088', pch=20, cex=.5)
n=table(p2$peak_type)
legend("topleft", paste(names(n), " (n=", n,")", sep=""), col=c('#0000aa66','#0000ff66', '#ff000088','#00ff0088'), pch=20, bty='n')
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)


# proximal peaks into different peak type (unique vs. common)
p1=subset(peaks1, inpromoter=="proximal")
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(subset(p1, peak_type=="common_peak1", c(A_rescaled, M_rescaled)), col='#0000aa66', pch=20, cex=(p1$summit_height[p1$peak_type=="common_peak1"]/200)^2+0.3, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Proximal H3K4me3 peaks (n=",nrow(p1),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
points(subset(p1, peak_type=="common_peak2", c(A_rescaled, M_rescaled)), col='#0000ff66', pch=20, cex=(p1$summit_height[p1$peak_type=="common_peak2"]/200)^2+0.3)
points(subset(p1, peak_type=="unique_peak1", c(A_rescaled, M_rescaled)), col='#ff000088', pch=20, cex=(p1$summit_height[p1$peak_type=="unique_peak1"]/200)^2+0.3)
points(subset(p1, peak_type=="unique_peak2", c(A_rescaled, M_rescaled)), col='#00ff0088', pch=20, cex=(p1$summit_height[p1$peak_type=="unique_peak2"]/200)^2+0.3)
n=table(p1$peak_type)
legend("topleft", paste(names(n), " (n=", n,")", sep=""), col=c('#0000aa66','#0000ff66', '#ff000088','#00ff0088'), pch=20, bty='n')
legend("bottomright", title="H3K4me3 peak height", title.adj=0.5, legend=c(50,100,200,400), pt.cex=(c(50,100,200,400)/200)^2+0.3, col="#999999", pch=20,  horiz=T, bty='n')
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

# distal peaks into different peak type (unique vs. common)
p2=subset(peaks1, inpromoter=="distal")
par(mar=c(4,4,4,1))
layout(matrix(seq(2),nrow=1,ncol=2),widths=c(3,0.5),heights=1)
plot(subset(p2, peak_type=="common_peak1", c(A_rescaled, M_rescaled)), col='#0000aa66', pch=20, cex=(p2$summit_height[p2$peak_type=="common_peak1"]/200)^2+0.3, xlab="A", ylab="M", xlim=range(peaks$M), main=paste("Distal H3K4me3 peaks (n=",nrow(p2),")\nSignificant peaks: MACS_FDR<10% and fold_enrichment >4",sep=""))
points(subset(p2, peak_type=="common_peak2", c(A_rescaled, M_rescaled)), col='#0000ff66', pch=20, cex=(p2$summit_height[p2$peak_type=="common_peak2"]/200)^2+0.3)
points(subset(p2, peak_type=="unique_peak1", c(A_rescaled, M_rescaled)), col='#ff000088', pch=20, cex=(p2$summit_height[p2$peak_type=="unique_peak1"]/200)^2+0.3)
points(subset(p2, peak_type=="unique_peak2", c(A_rescaled, M_rescaled)), col='#00ff0088', pch=20, cex=(p2$summit_height[p2$peak_type=="unique_peak2"]/200)^2+0.3)
n=table(p2$peak_type)
legend("topleft", paste(names(n), " (n=", n,")", sep=""), col=c('#0000aa66','#0000ff66', '#ff000088','#00ff0088'), pch=20, bty='n')
legend("bottomright", title="H3K4me3 peak height", title.adj=0.5, legend=c(50,100,200,400), pt.cex=(c(50,100,200,400)/200)^2+0.3, col="#999999", pch=20, horiz=T, bty='n')
image(1,1:nrow(peaks1),matrix(data=1:nrow(peaks1),ncol=nrow(peaks1),nrow=1),col=rev(rainbow(nrow(peaks1), start=0, end=4/6)), xlab="",ylab="",cex.axis=1,xaxt="n",yaxt="n", mar=c(4,0,2,2))
axis(2,seq(1, sum(peaks1$pvalue_MAnorm!=Inf & !is.na(peaks1$pvalue_MAnorm)),length.out=length(seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))),seq(0,max(peaks1$pvalue_MAnorm[peaks1$pvalue_MAnorm!=Inf], na.rm=T),20))
mtext('-log10(pvalue)', side=1, line=1, adj=1)

dev.off()
